disabled_rules:
    - identifier_name
    - cyclomatic_complexity
    - trailing_whitespace
    - vertical_whitespace

type_name:
    min_length: 3
    max_length: # warning and error
        warning: 50
