name: CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      working-directory: ./Algorithms
      run: |
        xcodebuild test -project Algorithms.xcodeproj -scheme AlgorithmsTests
